#免密支付最大限额
pay:
  nopassword:
    maxAmountPerDeal: 1000
  #免密支付每日最大限额
    maxAmountTotal: 5000
    user:
      name: 传智-虎哥
      age: 21
      girls:
        - 刘亦菲
        - 范冰冰
        - 柳岩
        - 古力娜扎
        - 迪丽热巴